### ISSUE TITLE
HSL Color Support

### ISSUE THREAD

**Issue by rihok** [pmndrs/leva#107]
Hey,

Would be great to also allow editing HSL color values (and HSLA). Ideally, it'd be possible to have a separation between defining the value in HSL or RGB, vs what the actual value contains. For example, I may like to write my color values in HSL, but the underlying value is hex or RGB.

Often apps that allow this, make switching between the input method pretty cumbersome, and the UI for the color picker in leva is very nice and simple so far, so hopefully a nice balance can be found. 👍 

Overall great work on this package btw. 💯

**Comment by dbismut** [comment]
Hi @rihok can you check PR #126 see if this is what you had in mind?

https://leva-git-feat-support-more-color-types-pmndrs.vercel.app/?path=/story/inputs-color--all-the-colors

**Comment by dbismut** [comment]
Added in 0.5.2, let me know how it goes!
