### ISSUE TITLE
API Request: onChange callback

### ISSUE THREAD

**Issue by Pomevak** [pmndrs/leva#115]
First of all, thanks for your great work, I really love it. 😊 

I just think it could be a good idea to add an `onChange` callback to input configurations, so that we can run some effects more directly.

**Comment by gsimone** [comment]
Could you describe your use case and what kind of API you have in mind?

**Comment by Pomevak** [comment]
> Could you describe your use case and what kind of API you have in mind?

I was originally using `react-three-gui`, but that package has several bugs and is poorly maintained. Then I found `leva` and decided to switch to it. So what I want is something similar to the [onChange api](https://github.com/birkir/react-three-gui#api) of react-three-gui's. 

My use case is to imperatively update properties in non react codes, which I think is hard to achieve based on current version of `leva`, so I want the `onChange` callback to help me achieve that.

**Comment by gsimone** [comment]
Oh, gotcha! We were looking into something similar to update threejs vectors/colors, so this is bound to come. Let us know if you have API ideas

**Comment by dbismut** [comment]
This can be done pretty easily I think, but I'm curious in which situation this wouldn't work?

```js
// possible today
const { color } = useControls({ color: '#ffa' })
const [threeColor] = useState(() => new THREE.Color(color))

React.useEffect(() => void threeColor.set(color), [color, threeColor])

// with onChange API?
const { color } = useControls({ color: {value: '#ffa', onChange: newValue => threeColor.set(newValue) } })
```

**Comment by gsimone** [comment]
the tiny problem is that the hook would cause a state change - unnecessary if, for example, all values are meant to be used imperatively anyway 

the subscribe based api we imagined at one point could be useful here

```js
useControls.subscribe({ color: '#ffa' }, values => void threeColor.set(values.color) )
```

**Comment by dbismut** [comment]
Ok so this would be a slice of the transient api then right? Meaning:

```js
const data = useControls({ color: {value: '#ffa', onChange: newValue => threeColor.set(newValue) }, number: 1 })

console.log(data.number) // 1
console.log(data.color)  // undefined
```

Is this also what you had in mind @Pomevak?
@gsimone do we need a hook handling both transient and reactive data?

**Comment by gsimone** [comment]
I would use a completely separate function like the example before (zustand 100%). Since we DO need a hook to declare the actual controls, we might need a dedicated one

```jsx
const subscribe = useControlsSubscription({ ... })

useEffect(() => {

   return subscribe(values => { ... })

}, [controls])
```

**Comment by dbismut** [comment]
We could also pass an option to the hook configuration, the same way we do with `store`.

```js
const subscribe = useControls(inputs, { /* store */, subscribe: true })
```

**Comment by gsimone** [comment]
And can we type is to that configuration returns the subscribe fn instead of the values? Because that would prevent footguns for ts users, which would be cool

**Comment by dbismut** [comment]
We absolutely can do this yes.

**Comment by gsimone** [comment]
Last weirdness is where users would want to use both imperative and state-based properties. They'd have to mix and match hooks

```jsx
const a = useControls({ ... })
const bSub = useControls({ ... }, { subscribe: true })
const c = useControls({ ... })

useEffect(() => bSub(v => ....))

return <mesh {...a} {...c} />
```

It's no biggie, but might inform our api design

**Comment by dbismut** [comment]
Yep... I agree this feels a bit weird, maybe another hook is better (even if in any case I think they will all resolve to the same base hook). I don't have a strong opinion on this.

**Comment by n1ru4l** [comment]
Would it be possible to omit any value that has an onChange handler defined in the returned object?

**Comment by dbismut** [comment]
0.7.0 is out and adds the `onChange` callback 🚀

Demo: https://codesandbox.io/s/leva-transient-x4rkw

**Comment by bwalton** [comment]
My apologies if this veers offtopic and into Discussion category:
Looking at the commits for onChange, would this be the way to relay a controls state elsewhere in a React app? Like keeping it in sync via Redux for instance?
