### ISSUE TITLE
Dependency array: Being able to update input settings, not just add or remove

### ISSUE THREAD

**Issue by guidovizosokognitiv** [pmndrs/leva#124]
As the description says it'd be great if the dependency hook could also update settings like options on the inputs. This would allow users to make data dynamic.

Here's a CodeSandbox example: https://codesandbox.io/s/admiring-currying-6en0y?file=/src/App.js

It'd be nice for the input to update with new options once the dependency changed.

**Comment by jeetiss** [comment]
I have this problem too

**Comment by dbismut** [comment]
Fixed in 0.6.3 by @guidovizoso 🎉

**Comment by jeetiss** [comment]
Awesome! thanks @guidovizoso 🙌🏻
