### ISSUE TITLE
scroll bar is flashing when collapsing the leva panel

### ISSUE THREAD

**Issue by n1ru4l** [pmndrs/leva#139]
See https://cdn.discordapp.com/attachments/804345339636219924/820241728233668668/Misc___Panel_options_-_Hide_Copy_Button_Storybook_-_Google_Chrome_2021-03-13_11-27-01.mp4

**Comment by dbismut** [comment]
@n1ru4l hey can you check #142 see if that fixes it? It does on Mac, but you know... Windows...
