### ISSUE TITLE
Issues building with Rollup and Yarn pnp

### ISSUE THREAD

**Issue by cef62** [pmndrs/leva#196]
I'm using `leva` in a few small projects, and I really love it!
Thank you so much for this great tool :)

Using `leva` alongside `yarn` with `pnp` enabled and `rollup`, I encountered issues when building the static bundle.
The issue is related to `leva`'s dependency to `@radix-ui/react-tooltip`.

You can see the message here:

<img width="1535" alt="Screenshot 2021-04-06 at 10 39 44" src="https://user-images.githubusercontent.com/129991/113685396-7e349b80-96c6-11eb-9949-47465f6077bf.png">

I created a repo to reproduce the issue: https://github.com/cef62/leva-radix-ui-issue

As a temporary solution, I'm forcing the sub-dependency `@radix-ui/react-tooltip` to the latest version using the `resolutions` field in my `package.json` file.

I want to open a PR to bump the nested dependencies to the latest version from `@radix-ui`.
Before doing it, I wanted to know if it's okay with your current plan or if you already have solutions planned.

**Comment by dbismut** [comment]
Hi @cef62 thanks for the issue, at the time the Modulz time released a 0.0.10 version that broke the build so I kept 0.0.9. I can update this now and run some tests on my end, will let you know when I'm done.

**Comment by cef62** [comment]
Thank you @dbismut

Please let me know if I can be of help.

**Comment by dbismut** [comment]
I'm taking the occasion for updating all the deps, so obviously some stuff breaks, but hopefully this should resolve pretty easily.

**Comment by dbismut** [comment]
@cef62 0.9.3 is out, let me know if it fixes it for you, and if so, I'll let you close the issue ;)

**Comment by cef62** [comment]
Thank you! 
Updating to `0.9.3` resolved the issue :)

You can see the working version here: https://github.com/cef62/leva-radix-ui-issue/tree/issue-fixed.

I'm closing the issue.
The resolution it's been super fast :)
