### ISSUE TITLE
Dependency array does not trigger re-render on string

### ISSUE THREAD

**Issue by raunofreiberg** [pmndrs/leva#207]
Hey 👋 

Thanks for the great library 🙏 

I've been playing around with it and found that the dependency array of `useControls` does not seem to trigger a re-render with primitive values? Hopefully not misusing it because it seems to work with `options`.

Here's a reproducable CodeSandbox. Notice that clicking the button does not change the input value:

https://codesandbox.io/s/crazy-feather-5u05k?file=/src/App.js

Thank you for taking a look!

**Comment by dbismut** [comment]
Hi @raunofreiberg, the deps array in useControls only updates the settings, not the value. There's a set function for this. I've amended your sandbox so that it's clear for you:

https://codesandbox.io/s/zen-elgamal-lfx46?file=/src/App.js
