### ISSUE TITLE
optional with onChange

### ISSUE THREAD

**Issue by n1ru4l** [pmndrs/leva#208]
It should be possible to get the `optional` and `disabled` state within onChange. Also `onChange` should be invoked when the `disabled` state changes.

```ts
const values = useControls({
  color: { value: "#f00", optional: true },
  vector: {
    value: [0, 0, 0],
    optional: true,
    disabled: true,
    onChange: (value, path, { disabled }) => {
      // do sth with the value
    }
  }
});
```

**Comment by dbismut** [comment]
Agreed, we can try to push this in #206 right?

**Comment by n1ru4l** [comment]
yes I can take care of this tomorrow
