### ISSUE TITLE
"THREE.WebGLRenderer: Context Lost" regression 0.9.4-0.9.6

### ISSUE THREAD

**Issue by mysterybear** [pmndrs/leva#213]
Hi,

I noticed when making this codesandbox https://codesandbox.io/s/github/mysterybear/r3f-image-crop?file=/src/App.js if I pin leva at 0.9.4 it's fine, if I use the latest 0.9.6 I get this `THREE.WebGLRenderer: Context Lost` error and the canvas blanks

**Comment by dbismut** [comment]
That's really weird... I can't really reproduce, the behavior seems erratic. There's no reason I can think of why Leva would produce this error...

I've forked the sandbox and got it working here: https://codesandbox.io/s/falling-feather-6j6ih, but I didn't make any change.

PS: note that you can use interval for that sort of insets inputs, have a look at the hero module on https://use-gesture.netlify.app, and click on activate bounds.

**Comment by mysterybear** [comment]
Very strange since in your sandbox and also if I download the sandbox code and run locally, I can reproduce! Must be something with my system?

![image](https://user-images.githubusercontent.com/50906986/114978100-a9667a00-9e80-11eb-8902-bc2a20b7fce3.png)

**Comment by mysterybear** [comment]
> PS: note that you can use interval for that sort of insets inputs, have a look at the hero module on https://use-gesture.netlify.app, and click on activate bounds.

Sorry I know this is aside from the issue but I don't understand - I've looked here https://github.com/pmndrs/react-use-gesture/blob/main/documentation/pages/HeroSandbox/index.js and here https://github.com/pmndrs/react-use-gesture/blob/main/documentation/pages/HeroSandbox/data.js and I can't see anything concerning any interval? Sorry if I'm missing something obvious, it's early :D

**Comment by dbismut** [comment]
No it's possible that 0.9.6 is breaking something, I've got a similar report on Discord I'm not sure what or why!

**Comment by dbismut** [comment]
Ok, silly mistake from my end when removing prefixes for styles, it's now resolved in 0.9.7. Sorry for the inconvenience!
