### ISSUE TITLE
onChange parameters `initial` and `fromPanel` returning undefined

### ISSUE THREAD

**Issue by zehfernandes** [pmndrs/leva#230]
Using leva@0.99

```js
const [data, set] = useControls(() => ({
  value: {
    value: 1,
    onChange: (value, { initial, fromPanel }) => {
      console.log(initial, fromPanel)
    },
  },
}))
```

Codesandbox: https://codesandbox.io/s/leva-issue-onchange-thgte

**Comment by dbismut** [comment]
@zehfernandes from 0.9.8 (I think!) it should now be:

```js
      onChange: (value, path, { initial, fromPanel }) => {
        console.log(path, initial, fromPanel);
      }
```

Again I apologize for the lack of clear documentation.

**Comment by zehfernandes** [comment]
Oh I see! Thanks for the quick response.

Example updated for further references:
https://codesandbox.io/s/leva-issue-onchange-thgte?file=/src/App.jsx
