### ISSUE TITLE
Same key name in nested folders

### ISSUE THREAD

**Issue by yuyao17** [pmndrs/leva#235]
Why can't there be multiple keys with the same key name in nested folders? 

Even the example here: https://leva.pmnd.rs/?path=/story/misc-folders--nested-folders

doesn't show 'Third Collapsed Folder' at all under the GUI since it violates that rule. Is this intended? Can think of many situations where there would be same key names under nested folders...

**Comment by dbismut** [comment]
The example is flawed, I will correct it.

The reason is pretty simple and is by design: since the hook returns the flattened schema, there can't be identical keys in a hook and the lib should throw a warning.

You can have identical nested keys in the panel, but just not in the same hook. 

```js
// don't do this
```

**Comment by yuyao17** [comment]
@dbismut I see. Is there a way to programatically call useControls? Say I have an deeply nested object with arbitrary number of data that can have the same keys, how would I structure that?

**Comment by dbismut** [comment]
Unfortunately there's no simple way to do this I'm afraid. You can try asking the question on the pmndrs discord linked from the Readme badges.
