### ISSUE TITLE
Flattened folder schema limits flexibility

### ISSUE THREAD

**Issue by r-oland** [pmndrs/leva#259]
It would be nice if we could have the ability to use the same key multiple times within a single hook. I now run into the problem where nested grouping doesn't really make for elegant code. ⬇️ 

**Current solution (Not bad but gets ugly on a larger scale)**
```
export default function Example() {
  const { amb_intensity, dir_position, dir_intensity } = useControls('lights', {
    ambient: folder({
      amb_intensity: 0.1,
    }),
    dirLight: folder({
      dir_position: [0, 10, 0],
      dir_intensity: 0.4,
    }),
  });

  return (
    <>
      <ambientLight intensity={amb_intensity} />
      <directionalLight position={dir_position} intensity={dir_intensity} />
    </>
  );
}
```

**A more elegant solution**
```
export default function Example() {
  const { ambient, dirLight } = useControls('lights', {
    ambient: folder({
      intensity: 0.1,
    }),
    dirLight: folder({
      position: [0, 10, 0],
      intensity: 0.4,
    }),
  });

  return (
    <>
      <ambientLight {...ambient} />
      <directionalLight {...dirLight} />
    </>
  );
}
```

Could we maybe add a toggle to make this kind of behaviour available? Otherwise, maybe a solution where we can group multiple entities from another useControls hook or the Leva component? 

Other than that, great library! ⭐

**Comment by dbismut** [comment]
I understand the issue, and this has been a design decision early on. Not saying that this can't be changed though. 

I would argue that you could achieve a more elegant solution with the existing API though:

```js

const ambient = useControls('lights.ambient',  { intensity: 0.1 })

const dirLight = useControls('lights.dirLight', { position: [0, 10, 0], intensity: 0.4 })
```

... which I feel is pretty acceptable.

**Comment by r-oland** [comment]
I agree. that's a really nice solution! Good work 🚀
