### ISSUE TITLE
warning about subscribeWithSelector when using onChange

### ISSUE THREAD

**Issue by souporserious** [pmndrs/leva#263]
Not sure why this is happening, it looks like it's possibly coming from `zustand`? This currently happens with React `17.0.2` when using the `onChange` option for inputs.

![console warning about subscribeWithSelector](https://user-images.githubusercontent.com/2762082/139730094-86be115c-baa4-47f1-a3e9-949afcc1782d.png)

**Comment by DennisSmolek** [comment]
This can be closed, it's related to an older version of Leva with a newer version of Zustand. Current versions have made the correct change
