### ISSUE TITLE
Tooltips don't work when input disabled

### ISSUE THREAD

**Issue by jorgenbuilder** [pmndrs/leva#264]
Hovering the label of a disabled input:
![image](https://user-images.githubusercontent.com/60938577/139733925-d64d2836-e706-4dca-8fa8-286ab044029a.png)

Hovering the label an input that is not disabled:
![image](https://user-images.githubusercontent.com/60938577/139734024-bc597902-1fae-49be-894b-2b41d6246d60.png)

**Comment by dbismut** [comment]
Should be fixed
