### ISSUE TITLE
Is there a way to disable a button and enable it on a certain condition?

### ISSUE THREAD

**Issue by marcelpi** [pmndrs/leva#268]
Hi guys,

Was just wondering if I could disable a button by default and then enable it if certain criteria is met?

Please let me know if there's any way to do it.
Thank you.

**Comment by dbismut** [comment]
Yes, you should be able to pass a dependency array as the last argument for `useControls`. 

That will force Leva to rebuild the schema (settings only, not values but `disabled` is a setting so that should work in your case). 

Therefore you just have to pass the same variable that toggles the `disabled` state to the deps array.

**Comment by marcelpi** [comment]
Thanks for replying.



When dealing with an input you just add the disabled property to the object.

```
const [controls, setControls] = useControls(() => ({

    density: { value: 1, min: 1, max: maxDensity, step: 1, disabled: true }

}), [deps])
```


In the case of a button I'm not sure where to add the disabled property since the button is a function, not an object:

```
const [controls, setControls] = useControls(() => ({

    'remove edit': button(() =>
    {
        doSomething()
    })

}), [deps])
```

Please let me know if there's any way to do it.
Cheers.


> Yes, you should be able to pass a dependency array as the last argument for `useControls`.
> 
> That will force Leva to rebuild the schema (settings only, not values but `disabled` is a setting so that should work in your case).
> 
> Therefore you just have to pass the same variable that toggles the `disabled` state to the deps array.

**Comment by dbismut** [comment]
Indeed you're right. As much as it is possible to disable a regular input, buttons don't have such option. I'll reopen and mark this as an enhancement request.

In the meantime you can decide to add or remove the button.

**Comment by dbismut** [comment]
Latest release gives `button` a second argument so you can do:

```js
useControls({ myButton: button(() => alert('hey'), { disabled: true }) })
```

**Comment by marcelpi** [comment]
That is awesome, thanks a lot David! Much appreciated.
