### ISSUE TITLE
Leva portability to SolidJS

### ISSUE THREAD

**Issue by davedbase** [pmndrs/leva#283]
Hailing from the SolidJS core. I maintain a project called Solid Primitives which is basically a hook library specific to SolidJS. We're building a demo platform to show off how hooks work and I was looking for an excellent control/pop-up utility. Leva looks absolutely gorgeous and would be a great candidate to port.

You may not heard of Solid but we're a reactivity library that uses JSX. It seems like with a bit of effort Leva might actually work in Solid (with a bit of effort). Digging through the source there are some heavier dependencies that might be blockers ie. Radix, React Icons and even Storybook support.

I was curious if someone could provide me with some information on roadmap or maybe a guesstimate of when Leva might hit 1.0. At that point I'd consider a port.

Thanks :-)

**Comment by dbismut** [comment]
+ @gsimone 

Hi @davedbase, thanks for your interest.

So indeed, there was a plan to make Leva hit 1.0 with a full rewrite. Ideally we would try to separate the logic between the data and the views a bit more, possibly in two different packages.

There's also the plan of making Leva work in a vanilla environment, possibly using Preact so that the bundle is lighter than when using React. But the core of Leva would still be coded in React.

If you'd like to rewrite Leva in SolidJS from the ground up, I guess the React dependencies that would require some efforts to port would be:

```js
"@radix-ui/react-portal" // could be trivial if there's a similar Portal concept in SolidJS
"@radix-ui/react-tooltip" // it's actually a fairly complex UI component as it detects window edges collision but the basic implications could be fairly straightforward
"@stitches/react" // this exists as a vanilla package I think
"@use-gesture/react" // this exists as a vanilla package
"react-colorful" // fairly complex package to handle colors
"react-dropzone" // fairly complex package to handle file uploads
```

Let me know ;)

**Comment by davedbase** [comment]
There's quite a bit of React baggage there, hehe. Probably a bit more than usual but nothing too crazy maybe.

Solid's surface API is almost similar to React, we've heard of people porting large projects within days so I'm not turned off by the effort. Uses JSX and hooks in some cases it's even faster because we have no hook rules or gotchas.

Looking at the dependency list you mentioned:

- `@radix-ui/react-portal`- Yeah we have the concept of portal not sure what the radix version is doing though
- `@radix-ui/react-tooltip` - We have Tooltip replacement (solid-tippy)
- `@stitches/react` - Solid Stitches almost done (https://github.com/modulz/stitches/pull/819)
- `@use-gesture/react` - We have our own hooks library with gestures
- `react-colorful` - Looks like it would take about 2-3 days to port
- `react-dropzone` - Could be replaced with solid-dnd or our Solid Primitives replacement

This could be a fun project. The UI is fantastic and it works really well. I'l actually looking for a solution for my upcoming Solid Primitives project (https://github.com/davedbase/solid-primitives). We're building a whole fleshed out demo platform for each one, I was hoping to use Leva for editing the test options.

Once you hit 1.0 I'd likely fork it and replace all the React internals to my needs. You could also ship Leva as a WebComponents so that they can be used agnostically of ones own framework setup. That would solve my problem at least.

Thanks and keep up the great work!

**Comment by davedbase** [comment]
Looks like the Solid ecosystem is already eating pieces of the dependencies ie. solid-colorful now exists. There's even a solid-leva in early dev https://github.com/devinxi/vinxi/tree/main/packages/solid-leva.

I'll close this out since we're on our way with this. Thanks keep up the good work in React-land! :-)
