### ISSUE TITLE
Sibling folders are not displayed

### ISSUE THREAD

**Issue by utileetdulce** [pmndrs/leva#285]
In this storybook example the sibling folder 'Third Collapsed Folder' is not shown:
storybook url: https://leva.pmnd.rs/?path=/story/misc-folders--nested-folders
storybook code: https://github.com/pmndrs/leva/blob/main/packages/leva/stories/Folder.stories.tsx#L81

**Comment by dbismut** [comment]
Hi, good catch!
But that's not a bug, just a poorly designed story which I'm fixing. Since the Third Collapsed Folder shares the same value keys as its sibling, it is ignored. There's a warning about this in the console, so all clear!

**Comment by utileetdulce** [comment]
Thank you for your explanation! I had indeed overlooked the console warning, but that explains the problems I am having specifying the x,y,z values of many 3D objects. Is there an alternative to renaming all keys?

**Comment by dbismut** [comment]
Yes there is. You can't use the similar keys in the same hook, but you can do:

```js
const v1 = useControls({ xyz: {x: 0, y: 0, z: 0} })
const v2 = useControls({ xyz: {x: 0, y: 0, z: 0} })

console.log(v1.xyz, v2.xyz)
```

Same using folders:

```js
const v1 = useControls('folder1', { xyz: {x: 0, y: 0, z: 0} })
const v2 = useControls('folder2', { xyz: {x: 0, y: 0, z: 0} })

console.log(v1.xyz, v2.xyz)
```

**Comment by utileetdulce** [comment]
many thanks!
