### ISSUE TITLE
How to access values from button callback?

### ISSUE THREAD

**Issue by cyan0n** [pmndrs/leva#288]
```TS
const  { num, button } = useControls({
    num: 0,
    button: button(() => console.log(num)
});
```
How can I access the current value of `num` from inside the callback inside `button`?
I only get the initial value on `num` even after updating the value from the leva UI panel

**Comment by dbismut** [comment]
Interesting. There's no straightforward solution to this (except using dependencies), but we could pass values as the first argument of the button callback. Let me see what we can do.

**Comment by dbismut** [comment]
In `0.9.18`:

```ts
const values = useControls({
  number: 3,
  foo: button((get) => alert(`Number value is ${get('number').toFixed(2)}`)),
})
```

**Comment by nomentech** [comment]
Add 'Folder Name' to useControls, the get function will return 'undefined' instead of 3

const values = useControls(**'Folder Name'**, {
  number: 3,
  foo: button((get) => alert(\`Number value is ${get('number').toFixed(2)}\`)),
})

**Comment by dbismut** [comment]
@nomentech The key you're passing to `get` is actually a path. Therefore when in a folder, you need to prefix the key with the folder path. 

In this case `get("folder name.number")` should work.

**Comment by nomentech** [comment]
yep, it works. Thanks.
