### ISSUE TITLE
Multiple separate panes

### ISSUE THREAD

**Issue by r0gi** [pmndrs/leva#293]
Is there any way to have multiple unrelated panes? I want to use this library to create several unique forms to send multiple ajax requests.

**Comment by dbismut** [comment]
https://codesandbox.io/embed/github/pmndrs/leva/tree/main/demo/src/sandboxes/leva-advanced-panels?codemirror=1

**Comment by r0gi** [comment]
Thank you for the quick response, this works well.
The [advanced/controlled-inputs](https://github.com/pmndrs/leva/blob/main/docs/advanced/controlled-inputs.md) doc has a note:
> This page should also probably talk about multi-panes

Maybe should have another markdown file under the advanced folder that discusses multiple panes, with that example? I can create a pull request for this if you want.

**Comment by dbismut** [comment]
Sûre, that would be awesome! Note that that there is also a use case where Leva can be used as a UI tool (also using multiple panes).

https://codesandbox.io/embed/github/pmndrs/leva/tree/main/demo/src/sandboxes/leva-ui
