### ISSUE TITLE
How to change the position of a floating leva panel

### ISSUE THREAD

**Issue by alejandroastudillo** [pmndrs/leva#302]
Hello,

I am trying to set a custom position (or at least some margins) to a leva panel. My application has a header of height `7vh` and the leva panel is laying behind it even though the leva panel is being created in a component that already has a top margin of `7vh`.
I've been trying including some styles to a div around Leva and LevaPanel (having the Leva instance inside and outside the div) but haven't achieved to move the panel so far.

Here is a basic code example:

```javascript
const InputsPanel = () => {
  const myStore = useCreateStore();
  
  const controls = useControls({
    Name: "Name",
    Checked: true,
  }, { store: myStore });

  return (
    <>
        <div
          style={{
            position: 'absolute',
            top: '7vh',
            marginTop: '7vh'
          }}
        >

        <Leva />
        <LevaPanel
          store={myStore}
          titleBar={{ title: "Settings", drag: true, filter: false }}
        />
      </div>
    </>

  );
};
```
Is there a way to include such re-positioning of the Leva panels or some margin to them? (maybe using themes?)

Thanks in advance.

**Comment by dbismut** [comment]
You can wrap the panel inside your node (like a div) and use the fill prop.

```html
<div> <!-- you control the position of that div>
  <Leva fill />
</div>
```
