### ISSUE TITLE
Bug: Disabled input values can be mutated via keyboard

### ISSUE THREAD

**Issue by Sec-ant** [pmndrs/leva#309]
The disabled input can be focused using `tab` or `shift`+`tab`, and then mutated using keyboard shortcuts and keys.

Demo GIF:
![demo](https://user-images.githubusercontent.com/10386119/154837361-fdd3aae2-f5ea-4fd0-8ca3-fd645e5afa4f.gif)

Demo Code:
[![Edit upbeat-brook-2543bx](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upbeat-brook-2543bx?fontsize=14&hidenavigation=1&theme=dark)

**Comment by dbismut** [comment]
@Sec-ant thanks for reporting this, it should now be fixed!

**Comment by Sec-ant** [comment]
> @Sec-ant thanks for reporting this, it should now be fixed!

Much obliged. Thank you, sir!
