### ISSUE TITLE
Easy way to destroy useControls

### ISSUE THREAD

**Issue by LuckyPigeon** [pmndrs/leva#323]
## Description
`useControls` seems not destroy itself after page refresh, is there's an easy way to destroy manual, or we must write it in a class of `React.Component`?

## Way to reproduce
Here's my [codesandbox](https://codesandbox.io/s/flamboyant-allen-rl9uzr?file=/src/App.tsx), you can see more and more `useControls` are created by refresh the page (three more console.log pop up after one more refresh).

**Comment by dbismut** [comment]
Your sandbox doesn't event use leva.

**Comment by LuckyPigeon** [comment]
@dbismut 
I've updated `codesandbox`, please check.

**Comment by dbismut** [comment]
I don't understand the problem.

**Comment by LuckyPigeon** [comment]
@dbismut 
I miss understand some of my code, now it solved! Thanks for your time!
