### ISSUE TITLE
This problem occurred when I upgraded to react 18

### ISSUE THREAD

**Issue by WaterSeeding** [pmndrs/leva#326]
![1](https://user-images.githubusercontent.com/31184164/162880708-820e73cf-5c2c-4f33-8f71-a1b7a249aa7d.jpg)
![2](https://user-images.githubusercontent.com/31184164/162880730-862d23b3-c2cb-4304-a016-0c8af672c177.jpg)

**Comment by marcelpi** [comment]
I'm getting the same error and wanted to post an issue. It seems someone else got it.

**Comment by dbismut** [comment]
Yes, Leva isn't fully compatible with React 18 yet. But this throws a warning in dev mode and that's it for now, so nothing critical.

**Comment by baranelitez** [comment]
> Yes, Leva isn't fully compatible with React 18 yet. But this throws a warning in dev mode and that's it for now, so nothing critical.

nothing critical? I think the app will run on some kind of compatibility mode for backwards compatibility instead of just displaying a warning.

**Comment by dbismut** [comment]
@baranelitez what's the question?

1. There's an ongoing PR for React 18. 

2. If you mount Leva yourself as in [here](https://github.com/pmndrs/leva/blob/main/docs/configuration.md), you'll suppress the warning.

3. If you let Leva auto mount, then only the panel will behave as in React 17.
