### ISSUE TITLE
update @stitches version

### ISSUE THREAD

**Issue by Sec-ant** [pmndrs/leva#332]
[stitches v1.2.8](https://github.com/modulz/stitches/releases/tag/v1.2.8) fixed ["length is declared here" issue](https://github.com/modulz/stitches/issues/947) with TS 4.6. I use leva/plugin to style some of my components and am geting errors with TS 4.6.
![image](https://user-images.githubusercontent.com/10386119/165711622-9d96b9b2-07ed-4e04-ab5c-ff663ccbf4a6.png)

**Comment by gsimone** [comment]
Want to make a PR for this?

**Comment by Sec-ant** [comment]
@gsimone done :)

**Comment by Sec-ant** [comment]
@gsimone A maybe non-relavent and stupid question: how am I going to use the unreleased leva repo in my project? A direct `yarn build` in my forked leva repo reported this issue https://github.com/microsoft/TypeScript/issues/42873 
![image](https://user-images.githubusercontent.com/10386119/165934613-618f1d88-fd6b-4ee3-92e4-5c8e55073c00.png)

**Comment by dbismut** [comment]
@Sec-ant you should be able to install a package from a pull request.
