### ISSUE TITLE
Supporting % (and other non-alphanumeric) suffix in number

### ISSUE THREAD

**Issue by Corei13** [pmndrs/leva#349]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `leva@0.9.27` for the project I'm working on.

I have some value in the format _x%_ that I want to keep as string, but leva was parsing them as numbers without any suffix.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/leva/src/components/Number/number-plugin.ts b/node_modules/leva/src/components/Number/number-plugin.ts
index ce107ad..415d611 100644
--- a/node_modules/leva/src/components/Number/number-plugin.ts
+++ b/node_modules/leva/src/components/Number/number-plugin.ts
@@ -21,7 +21,7 @@ export const normalize = ({ value, ...settings }: NumberInput) => {
   const _value = clamp(parseFloat(value as string), min, max)
   let suffix
   if (!Number.isFinite(value)) {
-    const match = String(value).match(/[A-Z]+/i)
+    const match = String(value).match(/[A-Z%]+/i)
     if (match) suffix = match[0]
   }
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by dbismut** [comment]
@Corei13 thanks for spotting this. Should be fixed in latest leva release (supporting all kinds of units).

```js
  let _value = parseFloat(value as string)
  const suffix = typeof value === 'string' ? value.substring(('' + _value).length) : undefined
  _value = clamp(_value, min, max)
```
