### ISSUE TITLE
General usage question - date pickers

### ISSUE THREAD

**Issue by tonysepia** [pmndrs/leva#382]
Hello! I really like the look of the library and it would be awesome to use something this beautiful in my next project.
I had a look through the components and can't see any datepickers. 

How do leva users get around the lack of datepickers in the library?

Thanks!

**Comment by alex-streza** [comment]
Hi there @tonysepia, indeed there is no included component or plugin available for date related pickers/calendar.

Fortunately there is a way to create your own inputs with a custom plugin that's not well documented other than this [demo example](https://github.com/pmndrs/leva/tree/main/demo/src/sandboxes/leva-custom-plugin).

I created here a CodeSandbox for a [leva-custom-date-plugin](https://codesandbox.io/s/leva-custom-date-plugin-h1f1ym?file=/src/App.tsx) and will open a PR with a custom date plugin after I run some benchmarks, understand the data flow better to decide whether it makes sense to such input for the scope of this library.

**Comment by tonysepia** [comment]
Thank you for the demo! Much appreciated!
