### ISSUE TITLE
onEditEnd is not giving the update state variable...

### ISSUE THREAD

**Issue by kkbandaru** [pmndrs/leva#398]
i followed this sample in the below...

https://leva.pmnd.rs/?path=/story/misc-input-options--on-edit-start-on-edit-end

here is my codebox link

https://codesandbox.io/s/levasandbox-5bv9lc?file=/src/App.js

in onEditEnd  the updated state variable value is not coming as expected.  is there some thing i am doing wrong...

**Comment by marbilher** [comment]
If you haven't take a look at the code behind the storybook examples yet check this out: https://github.com/pmndrs/leva/blob/792e70221d88835d7e06ae7ac9e5eedda2519cd5/packages/leva/stories/input-options.stories.tsx

**Comment by dbismut** [comment]
Closing since this is not using the API as it should. onEditEnd returns the update value similarly to onEditStart. What you're expecting here is useState to behave synchronously. Nothing to do with Leva ;)
